#!/usr/bin/env python3
"""
Output Generators - Policy Output File Generation Utilities

This module provides utilities for generating output files from policy structures,
including YAML and Rego format generation.

Functions:
    - generate_yaml_output: Generate YAML policy file content
    - generate_realm_roles_rego: Generate Rego content for user-to-realm-roles mapping
    - generate_privileges_rego: Generate Rego content for privileges mapping
    - generate_default_rego: Generate Rego content for deny-by-default behavior
    - generate_policy_rego: Generate Rego content for access control policy
"""

from pathlib import Path
from typing import Any, Dict, Optional
import yaml

from aiac.pdp.policy.models import Policy


def generate_yaml_output(policy_structure: dict, description: str = "") -> str:
    """
    Generate YAML output from a policy structure.
    
    Args:
        policy_structure: Dictionary containing the policy structure
        description: Original policy description for comments
        
    Returns:
        Complete YAML policy file content with comments
    """
    # Create header comments
    header = """# Access Control Policy
# Maps user roles (realm roles) to specific privileges
# Format: user_role_name -> list of privilege mappings
# Each entry specifies: service (service name) and privilege (privilege name from that service)

"""
    
    # Add original policy description as comment
    if description:
        description_lines = description.strip().split('\n')
        header += "# Original Policy Description:\n"
        for line in description_lines:
            header += f"#   {line.strip()}\n"
        header += "#\n"
    
    # Generate YAML from policy structure
    yaml_content = yaml.dump(
        policy_structure,
        default_flow_style=False,
        sort_keys=False,
        allow_unicode=True
    )
    
    # Add footer
    footer = "\n# Generated by PolicyBuilder using LangGraph\n"
    
    # Combine all parts
    return header + yaml_content + footer


def generate_realm_roles_rego(user_to_roles: dict) -> str:
    """
    Generate Rego content for user-to-realm-roles mapping.
    
    Args:
        user_to_roles: Dictionary mapping usernames to lists of realm role names
        
    Returns:
        Rego file content as string
    """
    rego_content = """package authz.realm_roles

# Realm Roles Mapping
# Maps user names to lists of realm role names

realm_roles := {
"""
    
    # Build the dictionary entries
    user_entries = []
    for username in sorted(user_to_roles):
        username_escaped = username.replace('"', '\\"')
        roles = user_to_roles.get(username, [])
        role_list = []
        for role_name in roles:
            role_name_escaped = role_name.replace('"', '\\"')
            role_list.append(f'"{role_name_escaped}"')
        roles_str = ", ".join(role_list)
        user_entries.append(f'    "{username_escaped}": [{roles_str}]')
    
    # Join all entries with commas
    rego_content += ",\n".join(user_entries)
    rego_content += "\n}\n"
    
    return rego_content


def generate_privileges_rego(privileges_map: Dict[str, dict], scopes: list) -> str:
    """
    Generate Rego content for privileges mapping by service/client.

    Args:
        privileges_map: Dict mapping service IDs to their service info.
            Each value is ``{"service_type": str, "roles": [{"name": str, "description": str}]}``.
            service_type is a property of the service, not of individual roles.
        scopes: List of Scope objects with 'name' and 'description'

    Returns:
        Rego file content as string
    """
    rego_content = """package authz.privileges

# Service Privileges Mapping
# Maps service/client IDs to their available privileges

"""

    # Create a list of scope names for inclusion in privileges
    scope_names = [scope.name for scope in scopes]

    for service_name, service_info in privileges_map.items():
        rego_content += f'service["{service_name}"] := [\n'
        for priv in service_info["roles"]:
            priv_name = priv.get("name", "")
            priv_desc = priv.get("description", "")
            # Escape quotes in description
            priv_desc = priv_desc.replace('"', '\\"')
            
            rego_content += f'    {{\n'
            rego_content += f'        "name": "{priv_name}",\n'
            rego_content += f'        "description": "{priv_desc}",\n'
            rego_content += f'        "scopes": [\n'
            # Add all available scopes to each privilege
            for scope_name in scope_names:
                scope_name_escaped = scope_name.replace('"', '\\"')
                rego_content += f'            "{scope_name_escaped}",\n'
            rego_content += '        ]\n'
            rego_content += f'    }},\n'
        rego_content += "]\n\n"
    
    return rego_content


def generate_default_inbound_rego() -> str:
    """
    Generate Rego content for deny-by-default behavior.
    
    Returns:
        Rego file content as string
    """
    return """package authbridge.inbound.request

default allow := false
"""

def generate_default_outbound_rego() -> str:
    """
    Generate Rego content for deny-by-default behavior.
    
    Returns:
        Rego file content as string
    """
    return """package authbridge.outbound.request

default allow := false
"""


def generate_policy_rego(
    policy_structure: dict,
    service_filter: str,
    service_types: Dict[str, str],
    description: str = "",
) -> str:
    """
    Generate Rego content for the access control policy.

    Converts the policy structure (role -> privileges) into Rego allow rules.
    Each rule checks if the user has the required role and matches the service/privilege.

    Args:
        policy_structure: Dictionary with 'policy' key containing role-to-privileges mapping.
            Privilege dicts contain only 'service' and 'privilege' keys.
        description: Original policy description for comments
        service_filter: If provided, only generate rules for this specific service
        service_types: Dict mapping service IDs to their type ('Tool' or 'Agent').
            service_type is a property of the service, not of individual privileges.
            Used to determine the protocol field in Rego rules ('mcp' for Tool, 'a2a' for Agent).
            Defaults to 'a2a' when a service is not present in the map.

    Returns:
        Rego file content as string
    """
    package = "outbound" if service_types.get(service_filter) == "Tool" else "inbound"

    rego_content = f"""package authbridge.{package}.request

import data.authz.realm_roles.realm_roles

# Access Control Policy
# Uses user -> realm roles mapping to authorize privileges
# Policy entries map realm role names to privilege mappings
# Each entry specifies: service (service name) and privilege (privilege name from that service)

"""
    
    # Add service filter info if applicable
    rego_content += f"# Service: {service_filter}\n"
    
    # Add original policy description as comment
    if description:
        description_lines = description.strip().split('\n')
        rego_content += "# Original Policy Description:\n"
        for line in description_lines:
            rego_content += f"#   {line.strip()}\n"
        rego_content += "#\n\n"
    
    # Extract policy from structure
    policy = policy_structure.get("policy", {})
    
    # Generate allow rules for each role and their privileges
    for role_name, privileges in policy.items():
        for priv in privileges:
            service = priv.get("service", "")
            privilege = priv.get("privilege", "")

            # Determine protocol from the service-level service_types map.
            # "mcp" for Tool type, "a2a" for Agent type (default).
            service_type = service_types.get(service)
            protocol = "mcp" if service_type == "Tool" else "a2a"
            service_name = "tool" if service_type == "Tool" else "agent"

            # Skip if service_filter is set and this privilege is for a different service
            if service != service_filter:
                continue
            
            # Escape quotes in service and privilege names
            service_escaped = service.replace('"', '\\"')
            privilege_escaped = privilege.replace('"', '\\"')
            
            role_name_escaped = role_name.replace('"', '\\"')
            
            rego_content += f"# User with role of **{role_name_escaped}**\n"
            rego_content += f"# may access {service_name} with id **{service_escaped}**\n"
            rego_content += f"# if the access token contains **{privilege_escaped}** scope\n"

            rego_content += f'allow if {{\n'
            rego_content += f'  "{role_name_escaped}" in object.get(realm_roles, input.identity.subject, [])\n'
            rego_content += f'  input.{protocol}.client_id == "{service_escaped}"\n'
            rego_content += f'  "{privilege_escaped}" in input.identity.scopes\n'
            rego_content += "}\n\n"
   
    return rego_content

def save_policy(policy: Policy, filepath: str = "access_control_policy.yaml") -> None:
    """
    Save a Policy as YAML to a file.

    Args:
        policy: Policy model instance
        filepath: Output file path
    """
    yaml_output = generate_yaml_output(
        {
            "policy": {
                realm_role: [
                    {"service": svc.serviceId or svc.name or svc.id, "privilege": priv.name}
                    for priv in privileges
                    for svc in priv.services
                ]
                for realm_role, privileges in policy.policy.items()
            }
        },
        policy.name,
    )
    with open(filepath, "w") as f:
        f.write(yaml_output)
    print(f"Access rules saved to {filepath}")


def save_policy_rego(
    policy: Policy,
    file_dir: str = "rego_policy",
    realm: str = "demo",
) -> None:
    """
    Save Rego files for realm roles, defaults, and per-service access policy.

    Creates:
    - realm_roles.rego: user → realm-role mapping
    - default_inbound.rego / default_outbound.rego: deny-by-default rules
    - generated_policy_<service>.rego: one allow-rule file per service in the policy

    Args:
        policy: Policy model instance
        file_dir: Directory to save Rego files
        realm: Keycloak realm name (used to fetch user-to-roles mapping)
    """
    from aiac.pdp.library.configuration.api import Configuration

    dir_path = Path(file_dir)
    dir_path.mkdir(parents=True, exist_ok=True)

    config_api = Configuration.for_realm(realm)
    user_to_roles: dict = {}
    for subject in config_api.get_subjects():
        user_to_roles[subject.username] = [role.name for role in subject.roles]

    realm_roles_path = dir_path / "realm_roles.rego"
    with open(realm_roles_path, "w") as f:
        f.write(generate_realm_roles_rego(user_to_roles))
    print(f"Realm roles Rego saved to {realm_roles_path}")

    default_inbound_path = dir_path / "default_inbound.rego"
    with open(default_inbound_path, "w") as f:
        f.write(generate_default_inbound_rego())
    print(f"Default Rego saved to {default_inbound_path}")

    default_outbound_path = dir_path / "default_outbound.rego"
    with open(default_outbound_path, "w") as f:
        f.write(generate_default_outbound_rego())
    print(f"Default Rego saved to {default_outbound_path}")

    # Deduplicate services by ID (Service is not hashable — cannot use a set)
    unique_services: Dict[str, Any] = {}
    for privs in policy.policy.values():
        for priv in privs:
            for svc in priv.services:
                svc_id = svc.serviceId or svc.name or svc.id
                unique_services[svc_id] = svc

    service_types = {svc_id: svc.type for svc_id, svc in unique_services.items()}
    policy_structure = {
        "policy": {
            realm_role: [
                {"service": svc.serviceId or svc.name or svc.id, "privilege": priv.name}
                for priv in privileges
                for svc in priv.services
            ]
            for realm_role, privileges in policy.policy.items()
        }
    }

    for svc_id in unique_services:
        policy_rego = generate_policy_rego(policy_structure, svc_id, service_types, policy.name)
        safe_name = svc_id.replace("/", "_").replace("\\", "_").replace(" ", "_")
        policy_path = dir_path / f"generated_policy_{safe_name}.rego"
        with open(policy_path, "w") as f:
            f.write(policy_rego)
        print(f"Generated policy Rego for service '{svc_id}' saved to {policy_path}")


# Made with Bob
