#!/usr/bin/env python3
"""
YAML policy file generation for the PDP (Policy Decision Point).

Public API:
    save_policy_yaml: Write a Policy model instance as a YAML file.
"""

import yaml

from aiac.policy.model.models import PolicyRule

__all__ = ["save_policy_yaml"]


def _generate_yaml_output(policy: list[PolicyRule]) -> str:
    header = """# Access Control Policy
# Maps user roles (realm roles) to specific privileges
# Format: user_role_name -> list of privilege mappings
# Each entry specifies: service (service name) and privilege (privilege name from that service)

"""
    yaml_content =""
    for r in policy:
        yaml_content += yaml.dump(
            r.model_dump(exclude_none=True),
            default_flow_style=False,
            sort_keys=False,
            allow_unicode=True,
        )

    footer = "\n# Generated by PolicyBuilder using LangGraph\n"
    return header + yaml_content + footer


def save_policy_yaml(policy: list[PolicyRule], filepath: str = "access_control_policy.yaml") -> None:
    """
    Save a Policy as YAML to a file.

    Args:
        policy: Policy model instance
        filepath: Output file path
    """
    yaml_output = _generate_yaml_output(policy)
    with open(filepath, "w") as f:
        f.write(yaml_output)
    print(f"Access rules saved to {filepath}")
